spring:
  datasource:
    #    url: "jdbc:mysql://localhost:3306/library"
    url: "jdbc:mysql://localhost:3306/testdata"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      generate-ddl: true
      #    hbm2ddl.auto: update
      ddl-auto: update # 테이블을 어떻게 처리할지 결정
    #    ddl-auto: none
    properties:
      hibernate:
        show_sql: true # 쿼리가 수행될때 SQL도 같이 보여줌
        format_sql: true # SQL을 보기 좋게 포멧팅
        dialect: org.hibernate.dialect.MySQL8Dialect # 여러 데이터베이스에 맞게 설정